### ISSUE TITLE
ReadMe File

### ISSUE THREAD

**Issue by fakharak** [gburtini/Learning-Library-for-PHP#11]
In your ReadMe file you have mentioned that PHP is wrong tool for Machine Learning. 

But in all popular benchmarks i see PHP 3 to 16 times faster than Python, when run different Algorithms.
See by yourself:
https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/php-python3.html
And also check Techempower for Swoole, and "php-ngx-pgsql". These are among top platforms.

Can you please omit that line ? Thanks in anticipation.

**Comment by gburtini** [comment]
I think it was probably more true in 2015 than it is today. 

Feel free to submit a pull request to revise or omit that line. I'm happy to drop some silly opinion I expressed a decade ago. :)
